---
title: "p8105_hw5_jx2371"
author: "Jingyu Xu"
date: "2018/11/4"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

#Problem1
##read and clean the data
First of all, a code chunck is used to create a dataframe containing all file names 
```{r}
library(tidyverse)
df = list.files(path = "./data")
```

Then, a code chunk is written to read the data in all the files and collected them in one dataset. A seires cleaning is made to the dataset.
```{r}
read_data = function(x){read_csv(file = str_c("./data/", x))%>%
    mutate(group_name=x)}
tidy_data = map(df, read_data)%>%
  bind_rows()%>%
  janitor::clean_names()%>%
  select(group_name, everything())%>%
  separate(group_name, into = c("group","subject"))%>%
  mutate(group = str_replace(group,"con","control"))%>%
  mutate(group = str_replace(group,"exp", "experimental"))%>%
  gather(key = week, value = data, week_1:week_8)%>%
  mutate(week = str_replace(week, "week_", ""))
```


